AuthenticationStorageSystem/EnlightenAss/Controllers/EntryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AssClassLibrary;

namespace EnlightenAss.Controllers
{
    public class EntryController : Controller
    {
        private DatabaseContext db = new DatabaseContext();

        /**
         * Returns entries where ProjectId = id
         */
        public ActionResult Index(int id = 0)
        {
            Project project = db.Projects.Find(id);

            //if project with id cannot be found return view of all entries (maybe should change to unable to find page)
            if (project == null) return PartialView(db.Entries.ToList());

            //Set viewbags values for the html to use (for html links and labels inside view)
            ViewBag.ProjectIdNum = id;
            ViewBag.ClientIdNum = project.ClientId;
            ViewBag.ProjectName = project.Name;
            ViewBag.ProjectNotes = project.Notes;

            //Client this project is under
            Client client = db.Clients.Find(project.ClientId);
            ViewBag.ClientName = client.Name;

            return PartialView(db.Entries.Where(i => i.ProjectId == id && !i.isArchived));
        }

        public ActionResult EntryDisplay(int id = 0)
        {
            Entry entry = db.Entries.Find(id);
            if (entry == null) return HttpNotFound();

            return PartialView(entry);
        }

        /**
         * Return all entries, rather than entiries under specific project
         */
        public ActionResult IndexAll(int id = 0)
        {
            return PartialView("DisplayAll", db.Entries.ToList());
        }

        public ActionResult Create(int id = 0)
        {
            //Drop down list for project names
            ViewBag.ProjectId = new SelectList(db.Projects, "ProjectId", "Name", id);
            
            //Drop down list for development states
            ViewBag.DevState = createDevStateList();

            //Id to return to
            ViewBag.ProjectIdNum = id;

            return PartialView();
        }

        /**
         * Some fields cannot be set by the user, therefore they are set statically 
         */
        [HttpPost]
        public ActionResult Create(Entry entry)
        {
            if (ModelState.IsValid)
            {
                entry.DateAdded = DateTime.Now;
                entry.isArchived = false;
                entry.LastModified = DateTime.Now;
                entry.LastModifiedBy = "X";
                db.Entries.Add(entry);
                db.SaveChanges();
                return RedirectToAction("Index", new { id = entry.ProjectId });
            }

            //Drop down list for project names
            ViewBag.ProjectId = new SelectList(db.Projects, "ProjectId", "Name", entry.ProjectId);
            //Drop down list for development states
            ViewBag.DevState = createDevStateList();

            return PartialView(entry);
        }


        /**
         * Edit Delete and details all in one view
         */
        public ActionResult Change(int id = 0)
        {
            Entry entry = db.Entries.Find(id);
            if (entry == null) return HttpNotFound();

            //Drop down list for project names
            ViewBag.ProjectId = new SelectList(db.Projects, "ProjectId", "Name", entry.ProjectId);

            return PartialView(entry);
        }

        /**
         * Some fields cannot be edited by the user, therefore they are changed statically 
         */
        [HttpPost]
        public ActionResult Change(Entry entry)
        {
            if (ModelState.IsValid)
            {
                Entry currentEntry = db.Entries.Find(entry.EntryId);
                currentEntry.Username = entry.Username;
                currentEntry.Password = entry.Password;
                currentEntry.Website = entry.Website;
                currentEntry.Notes = entry.Notes;
                currentEntry.isArchived = entry.isArchived;
                currentEntry.LastModified = DateTime.Now;
                currentEntry.LastModifiedBy = "X";
                db.Entry(currentEntry).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("EntryDisplay", new { id = entry.EntryId });
            }
            //Drop down list for project names
            ViewBag.ProjectId = new SelectList(db.Projects, "ProjectId", "Name", entry.ProjectId);

            return PartialView(entry);

        }

        /**
         * Do not know what these tags do...
         */
        [HttpPost, ActionName("Delete")]
        public ActionResult Delete(Entry entry)
        {
            Entry entryDelete = db.Entries.Find(entry.EntryId);
            int projectId = entryDelete.ProjectId; //Store parent directory for redirect action
            db.Entries.Remove(entryDelete);
            db.SaveChanges();
            return RedirectToAction("Index", new { id = projectId });
        }

        /**
         * Return a list of the three development states
         * Development, testing staging
         */
        private List<SelectListItem> createDevStateList()
        {
            //Drop down list for development states
            List<SelectListItem> devStates = new List<SelectListItem>();
            SelectListItem dev = new SelectListItem() { Text = "Development", Value = "Development" };
            SelectListItem testing = new SelectListItem() { Text = "Staging", Value = "Staging" };
            SelectListItem staging = new SelectListItem() { Text = "Production", Value = "Production" };
            devStates.Add(dev); devStates.Add(testing); devStates.Add(staging);
            
            return devStates;
        }

        //toggles the given entry's isArchived value
        public void toggleIsArchived(int id)
        {
            Entry currentEntry = db.Entries.Find(id);
            currentEntry.isArchived = !currentEntry.isArchived;
            db.Entry(currentEntry).State = EntityState.Modified;
            db.SaveChanges();
        }
        
        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

AuthenticationStorageSystem/EnlightenAss/Views/Entry/Change.cshtml
@model AssClassLibrary.Entry

<h3>Modifying Authentication Details</h3>

<div class="rightButtonGroup">
    <button type="button" class="btn btn-default btn-inverse" onclick="history.back();">Back</button>
</div>
<br />
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)

    <hr />

    @Html.HiddenFor(model => model.EntryId)

    <div class="editor-label">
        @Html.LabelFor(model => model.ProjectId, "Project")
    </div>
    <div class="editor-field; form-move-right">
        @Html.DropDownList("ProjectId", String.Empty)
        @Html.ValidationMessageFor(model => model.ProjectId)
    </div>
    <div class="editor-label">
        @Html.LabelFor(model => model.Username)
    </div>
    <div class="editor-field; form-move-right">
        @Html.EditorFor(model => model.Username)
        @Html.ValidationMessageFor(model => model.Username)
    </div>
    <div class="editor-label">
        @Html.LabelFor(model => model.Password)
    </div>
    <div class="editor-field; form-move-right">
        @Html.EditorFor(model => model.Password)
        @Html.ValidationMessageFor(model => model.Password)
    </div>    
    <div class="editor-label">
        @Html.LabelFor(model => model.DevState, "Development State")
    </div>
    <div class="editor-field; form-move-right">
        @Model.DevState
    </div><br>
    <div class="editor-label">
        @Html.LabelFor(model => model.Website)
    </div>
    <div class="editor-field; form-move-right">
        @Html.EditorFor(model => model.Website)
        @Html.ValidationMessageFor(model => model.Website)
    </div>
    <div class="editor-label">
        @Html.LabelFor(model => model.Notes)
    </div>
    <div class="editor-field; form-move-right">
        @Html.EditorFor(model => model.Notes)
        @Html.ValidationMessageFor(model => model.Notes)
    </div>    
    <div class="editor-label">
        @Html.LabelFor(model => model.isArchived)
    </div>    
    <div class="editor-field; form-move-right">
        @Html.EditorFor(model => model.isArchived)
        @Html.ValidationMessageFor(model => model.isArchived)
    </div>
    <!-- Having hidden fors stop the date modified and added labels changing to default time on validation fail -->
    @Html.HiddenFor(model => model.DateAdded)
    @Html.HiddenFor(model => model.LastModified)
	<br>
    <div class="editor-label">
        Date Added
    </div>
	<div class="editor-field; form-move-right">
		@Model.DateAdded
	</div>	
    <div class="editor-label">
        Last Modified
    </div>
	<div class="editor-field; form-move-right">
		@Model.LastModified
	</div>
    <br>

    <input class="btn btn-small btn-info save-button" type="button" value="Save Changes" onclick="ajaxSubmitForm(this)" />
            
}

<!-- Set selected input box -->
<script>
    $("#Username").focus();
</script>

<!-- Separate Form for deleting the item -->
@using (Html.BeginForm("Delete", "Entry", FormMethod.Post))
{
    @Html.HiddenFor(model => model.EntryId)
    <input type="button" value="Delete Entry" class="btn btn-small btn-danger delete-button" onclick="ajaxSubmitForm(this)" />
}

AuthenticationStorageSystem/EnlightenAss/Views/Entry/Create.cshtml
@model AssClassLibrary.Entry

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <h3>Creating New Entry</h3>
    
    <div class="rightButtonGroup">
        <button type="button" class="btn btn-default btn-inverse" onclick="history.back();">Back</button>
    </div>
    
    <br>
    <hr />

    <div class="editor-label">
        @Html.LabelFor(model => model.ProjectId, "Project")
    </div>
    <div class="editor-field; form-move-right">
        @Html.DropDownList("ProjectId")
        @Html.ValidationMessageFor(model => model.ProjectId)
    </div>

    <div class="editor-label">
        @Html.LabelFor(model => model.Username)
    </div>
    <div class="editor-field; form-move-right">
        @Html.EditorFor(model => model.Username)
        @Html.ValidationMessageFor(model => model.Username)
    </div>

    <div class="editor-label">
        @Html.LabelFor(model => model.Password)
    </div>
    <div class="editor-field; form-move-right">
        @Html.EditorFor(model => model.Password)
        @Html.ValidationMessageFor(model => model.Password)
    </div>
    
    <div class="editor-label">
        @Html.LabelFor(model => model.DevState, "Development State")
    </div>
    <div class="editor-field; form-move-right">
        @Html.DropDownList("DevState")
        @Html.ValidationMessageFor(model => model.DevState)
    </div>

    <div class="editor-label">
        @Html.LabelFor(model => model.Website)
    </div>
    <div class="editor-field; form-move-right">
        @Html.EditorFor(model => model.Website)
        @Html.ValidationMessageFor(model => model.Website)
    </div>

    <div class="editor-label">
        @Html.LabelFor(model => model.Notes)
    </div>
    <div class="editor-field; form-move-right">
        @Html.EditorFor(model => model.Notes)
        @Html.ValidationMessageFor(model => model.Notes)
    </div>

    <p>
        <input type="button" value="Create" onclick="this.disabled = true; ajaxSubmitForm(this);" class="btn btn-small btn-info create-button" />
    </p>
}

<!-- Set selected input box -->
<script>
    $("#Username").focus();
</script>


AuthenticationStorageSystem/EnlightenAss/Views/Entry/DisplayAll.cshtml
@model IEnumerable<AssClassLibrary.Entry>


    <h3>All Entries</h3>


<div class="rightButtonGroup">
    <button type="button" class="btn btn-default btn-inverse" style="margin-left:20px" onclick="requestItem('@ViewBag.ProjectIdNum', '/Entry/Create')">New Entry</button>
</div>
<br />
<p class="text-muted">@ViewBag.ProjectNotes</p>
<hr />


<table class="table table-bordered">
    <tr class="table-bordered headerRow">
        <th style="width: 300px;">
            @Html.DisplayNameFor(model => model.Username)
        </th>
        <th style="width: 100px;">isArchived</th>
    </tr>

    @{int counter = 0;}
    @foreach (var item in Model)
    {
        <tr class="@item.DevState" id="@counter" onclick="requestItem('@item.EntryId', '/Entry/EntryDisplay')">
            <td>
                @Html.DisplayFor(modelItem => item.Username)
            </td>
            <td class="archivetd" onclick="toggleIsArchived('@item.EntryId', 'Entry/toggleIsArchived', $(this).children(), true);">
                <input class="archiveCheckBox" type="checkbox" checked="@item.isArchived" onclick="toggleIsArchived('@item.EntryId', 'Entry/toggleIsArchived', this, false)"/>
            </td>
        </tr>
        counter++;
    }

</table>

AuthenticationStorageSystem/EnlightenAss/Views/Entry/EntryDisplay.cshtml
@model AssClassLibrary.Entry

<a onclick="home()"><i class="icon-large icon-home"></i></a>
<p>/ </p>

@if (Model.Project.Client.Name.Length > 30)
{
    <directory onclick="requestItem('@Model.Project.ClientId', '/Project/Index');"><a>
    @{Write(Model.Project.Client.Name.Substring(0, 27));}
    </a></directory>
}
else
{
    <directory onclick="requestItem('@Model.Project.ClientId', '/Project/Index');"><a>
    @{Write(Model.Project.Client.Name);}
    </a></directory>
}
/ 
@if (Model.Project.Name.Length > 30)
{
    <directory onclick="requestItem('@Model.ProjectId', '/Entry/Index');"><a>
        @{Write(Model.Project.Name.Substring(0, 27));}
        @{Write("...");}
        </a></directory>
}
else
{
    <directory onclick="requestItem('@Model.ProjectId', '/Entry/Index');"><a>
        @{Write(Model.Project.Name);}
        </a></directory>    
}
<p>/ </p>
<h3>@Model.Username</h3>

<a onclick="$('#link').show()"><i class="icon-large icon-magnet"></i></a>
<label id="link" style="display:none">/Home/Link/?url=/Entry/EntryDisplay&id=@Model.EntryId</label>
<script> getDomain(); </script>
<button id="upDirButton" style="display:none" type="button" onclick="requestItem('@Model.ProjectId', '/Entry/Index');"></button>

<div class="rightButtonGroup">
    <button type="button" class="editButton btn btn-default btn-inverse" onclick="requestItem('@Model.EntryId', '/Entry/Change')">Modify Entry</button>
    <button type="button" id="backLink" class="btn btn-default btn-inverse" style="margin-left:20px" onclick="history.back();">Back</button>
</div>
<br />
<p class="text-muted">@Model.Notes</p>
<hr />

<table class="table table-bordered">
    <tr class="table-bordered headerRow">
        <th style="width: 300px;">
            @Html.DisplayNameFor(model => model.Username)
        </th>
        <th style="width: 300px;">
            @Html.DisplayNameFor(model => model.Password)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Website)

        </th>
    </tr>
    <tr class="@Model.DevState">
        <td onclick="focusTextBox('username');">
            <input type="text" value="@Model.Username" id="username" readonly="true"/>
        </td>
        <td onclick="focusTextBox('password');">
            <input type="text" value="@Model.Password" id="password" readonly="true"/>
        </td>
        <td class="externalLink">
            <a class="externalLink" href="http://@Model.Website">@Model.Website</a>
        </td>
    </tr>
</table>

<script>
    function focusTextBox(element) {
        document.getElementById(element).focus();
        document.getElementById(element).select();
    }
    focusTextBox('password');
</script>

AuthenticationStorageSystem/EnlightenAss/Views/Entry/Index.cshtml
@model IEnumerable<AssClassLibrary.Entry>


@{
    <a onclick="home();"><i class="icon-large icon-home"></i></a>
    <p>/ </p>
    <directory onclick="requestItem('@ViewBag.ClientIdNum', '/Project/Index');"><a>
    @ViewBag.ClientName
    </a></directory>
    Write(" / ");
    <h3>@ViewBag.ProjectName</h3>
    Write(" / ");

    }

<a onclick="$('#link').show()"><i class="icon-large icon-magnet"></i></a>
<label id="link" style="display:none">/Home/Link/?url=/Entry/Index&id=@ViewBag.ProjectIdNum</label>
<script> getDomain(); </script>
<button id="upDirButton" style="display:none" type="button" class="btn btn-default btn-inverse" onclick="requestItem('@ViewBag.ClientIdNum', '/Project/Index');"></button>


<div class="rightButtonGroup">
    <button type="button" class="editButton btn btn-default btn-inverse" onclick="requestItem('@ViewBag.ProjectIdNum', '/Project/Change')">Modify Project</button>
    <button type="button" class="btn btn-default btn-inverse" style="margin-left:20px" onclick="requestItem('@ViewBag.ProjectIdNum', '/Entry/Create')">New Entry</button>
</div>
<br />
<p class="text-muted">@ViewBag.ProjectNotes</p>
<hr />


<table class="table table-bordered">
    <tr class="table-bordered headerRow">
        <th style="width: 300px;">
            @Html.DisplayNameFor(model => model.Username)
        </th>
        <th style="width: 300px;">
            @Html.DisplayNameFor(model => model.Notes)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Website)
        </th>
    </tr>

    @{int counter = 0;}
    @foreach (var item in Model)
    {
        
            <tr class="@item.DevState" id="@counter" onclick="requestItem('@item.EntryId', '/Entry/EntryDisplay')">
                <td>
                    @Html.DisplayFor(modelItem => item.Username)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Notes)
                </td>
                <td class="externalLink">
                    <a class="externalLink" href="http://@item.Website">@item.Website</a>
                </td>
            </tr>
            counter++;
        
    }

</table>